/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MovieEntry;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author User
 */
public class MovieEntry extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form MovieEntry
     */
    public MovieEntry() {
        initComponents();      
        Object col[] = {
            "id", "name", "genre", "year", "description", 
            "release_date", "budget", "language", "yearRestrict", "movieType", "movieLength"
        };
        model.setColumnIdentifiers(col);
        jTable1.setModel(model);
        conn = MovieEntry.ConnectDB();
        
        updateTable();
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnAddNew = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        movie_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        movie_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        movie_genre = new javax.swing.JTextField();
        movie_language = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        movie_release_date = new javax.swing.JTextField();
        movie_budget = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        movie_year = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        movie_year_restrict = new javax.swing.JTextField();
        movie_description = new javax.swing.JTextField();
        movie_length = new javax.swing.JComboBox<>();
        movie_type = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(1460, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setBackground(new java.awt.Color(51, 51, 51));
        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setForeground(new java.awt.Color(51, 51, 51));
        jbtnReset.setText("Reset All Input");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 180, 40));

        jbtnAddNew.setBackground(new java.awt.Color(51, 51, 51));
        jbtnAddNew.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnAddNew.setForeground(new java.awt.Color(51, 51, 51));
        jbtnAddNew.setText("Add New Movie");
        jbtnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddNewActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 180, 40));

        jbtnUpdate.setBackground(new java.awt.Color(51, 51, 51));
        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnUpdate.setForeground(new java.awt.Color(51, 51, 51));
        jbtnUpdate.setText("Update Movie");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 180, 40));

        jbtnExit.setBackground(new java.awt.Color(51, 51, 51));
        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(51, 51, 51));
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 180, 40));

        jbtnDelete.setBackground(new java.awt.Color(51, 51, 51));
        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDelete.setForeground(new java.awt.Color(51, 51, 51));
        jbtnDelete.setText("Delete Movie");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 180, 40));

        jbtnPrint.setBackground(new java.awt.Color(51, 51, 51));
        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnPrint.setForeground(new java.awt.Color(51, 51, 51));
        jbtnPrint.setText("Print Movie List");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 1430, 60));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie ID", "Movie name", "Movie genre", "Movie year", "Movie description", "Release date", "Movie budget", "Movie language", "Year restrict", "Movietype", "Movie length"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 27, 1400, 420));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 1430, 460));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        movie_id.setBackground(new java.awt.Color(51, 51, 51));
        movie_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        movie_id.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(movie_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 170, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Movie Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        movie_name.setBackground(new java.awt.Color(51, 51, 51));
        movie_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        movie_name.setForeground(new java.awt.Color(255, 255, 255));
        movie_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movie_nameActionPerformed(evt);
            }
        });
        jPanel3.add(movie_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 170, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Movie Year");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Movie Genre");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        movie_genre.setBackground(new java.awt.Color(51, 51, 51));
        movie_genre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        movie_genre.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(movie_genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 170, 40));

        movie_language.setBackground(new java.awt.Color(51, 51, 51));
        movie_language.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        movie_language.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(movie_language, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 170, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Release Date");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Movie Description");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        movie_release_date.setBackground(new java.awt.Color(51, 51, 51));
        movie_release_date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        movie_release_date.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(movie_release_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 170, 40));

        movie_budget.setBackground(new java.awt.Color(51, 51, 51));
        movie_budget.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        movie_budget.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(movie_budget, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 170, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Movie Budget");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        movie_year.setBackground(new java.awt.Color(51, 51, 51));
        movie_year.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        movie_year.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(movie_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 170, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Movie Language");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Movie type");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Movie length");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, -1, -1));

        movie_year_restrict.setBackground(new java.awt.Color(51, 51, 51));
        movie_year_restrict.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        movie_year_restrict.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(movie_year_restrict, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 220, 40));

        movie_description.setBackground(new java.awt.Color(51, 51, 51));
        movie_description.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        movie_description.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(movie_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 170, 40));

        movie_length.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        movie_length.setForeground(new java.awt.Color(255, 255, 255));
        movie_length.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select length", "<30 min", "~1 hour", ">1 hour" }));
        movie_length.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movie_lengthActionPerformed(evt);
            }
        });
        jPanel3.add(movie_length, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 130, 220, 40));

        movie_type.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        movie_type.setForeground(new java.awt.Color(255, 255, 255));
        movie_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select movie type", "Free", "Paid" }));
        movie_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movie_typeActionPerformed(evt);
            }
        });
        jPanel3.add(movie_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 80, 220, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Year restrict");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1430, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddNewActionPerformed
    DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
        mod.setRowCount(0);
               
        
        String sql = "INSERT INTO dataform(id, name, genre, year, description, release_date, budget, " 
                    +  "language, yearRestrict, movieType, movieLength)VALUES(?,?,?,?,?,?,?,?,?,?,?)";
            
        try
        {
            pst = conn.prepareStatement(sql);
            pst.setString(1, movie_id.getText());
            pst.setString(2, movie_name.getText());
            pst.setString(3, movie_genre.getText());
            pst.setString(4, movie_year.getText());
            pst.setString(5, movie_description.getText());
            pst.setString(6, movie_release_date.getText());
            pst.setString(7, movie_budget.getText());
            pst.setString(8, movie_year_restrict.getText());
            pst.setString(9, (String) movie_type.getSelectedItem());
            pst.setString(10, (String) movie_length.getSelectedItem());
            pst.setString(11, movie_language.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data is added");
            rs.close();
            pst.close();

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        updateTable();
        DefaultTableModel iModel = (DefaultTableModel) jTable1.getModel();
        
        if(jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Movie Entry update confirmed",
                        "MovieEntry System", JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_jbtnAddNewActionPerformed

    private void movie_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movie_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movie_nameActionPerformed

    private void movie_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movie_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movie_typeActionPerformed
    public static Connection ConnectDB() {
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:dataform.db"); //connect to database
            return conn;
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
       return null;
        }
    }
    
    public void updateTable() {
        conn = MovieEntry.ConnectDB();
        
        if (conn != null) {
            String sql = "Select id, name, genre, year, description,release_date, budget," 
                    +  "language, yearRestrict, movieType, movieLength from dataform";
            
        try
        {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            Object[] columnData = new Object[11];
            
        
            while (rs.next()) {
                columnData[0] = rs.getString("id");
                columnData[1] = rs.getString("name");
                columnData[2] = rs.getString("genre");
                columnData[3] = rs.getString("year");
                columnData[4] = rs.getString("description");
                columnData[5] = rs.getString("release_date");
                columnData[6] = rs.getString("budget");
                columnData[7] = rs.getString("language");
                columnData[8] = rs.getString("yearRestrict");
                columnData[9] = rs.getString("movieType"); 
                columnData[10] = rs.getString("movieLength");
                model.addRow(columnData);
            }
            rs.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
     
        }
 
     
        }
    }
    
    
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Exit?",
                "MovieEntry for",
               JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        
        MessageFormat header = new MessageFormat("Printing");
        
        MessageFormat footer = new MessageFormat("Page ({0, number, integer}");
        
        try {
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        }
        catch (java.awt.print.PrinterException e)
        {
            System.err.format("No printer found", e.getMessage());
        }
        
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
       try 
       {
           movie_id.setText(null);
           movie_name.setText(null);
           movie_genre.setText(null);
           movie_year.setText(null);
           movie_description.setText(null);
           movie_release_date.setText(null);
           movie_budget.setText(null);
           movie_year_restrict.setText(null);
           movie_language.setText(null);
           movie_type.setSelectedIndex(0);
           movie_length.setSelectedIndex(0);
       }
       catch (Exception e)
               {
                   JOptionPane.showMessageDialog(null, e);
               }
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed

        updateTable();
        DefaultTableModel iModel = (DefaultTableModel) jTable1.getModel();
        
        if(jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Movie Updated!",
                        "MovieEntry", JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
       conn = MovieEntry.ConnectDB();
        DefaultTableModel iModel = (DefaultTableModel) jTable1.getModel();
        
        String sql = "DELETE FROM dataform WHERE id = ?";
                 
              
        if (jTable1.getSelectedRow() == -1) {
            if(jTable1.getRowCount()==0) {
                         
                JOptionPane.showMessageDialog(null, "No data to delete", 
                        "Data Entry", JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(null, "Select a row to delete", 
                        "Movie Entry", JOptionPane.OK_OPTION);
            }
            }else{                                                             
                  model.removeRow(jTable1.getSelectedRow());                                  
               }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void movie_lengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movie_lengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movie_lengthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAddNew;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField movie_budget;
    private javax.swing.JTextField movie_description;
    private javax.swing.JTextField movie_genre;
    private javax.swing.JTextField movie_id;
    private javax.swing.JTextField movie_language;
    private javax.swing.JComboBox<String> movie_length;
    private javax.swing.JTextField movie_name;
    private javax.swing.JTextField movie_release_date;
    private javax.swing.JComboBox<String> movie_type;
    private javax.swing.JTextField movie_year;
    private javax.swing.JTextField movie_year_restrict;
    // End of variables declaration//GEN-END:variables
}
